name: chrome_extension
version: 0.3.1
description: A library for accessing the `chrome.*` APIs available in Chrome extensions.
homepage: https://github.com/xvrh/chrome_extension.dart
environment:
  sdk: '^3.3.1'

funding:
  - https://www.buymeacoffee.com/xvrh
  - https://github.com/sponsors/xvrh

dev_dependencies:
  analyzer:
  build_runner:
  checks:
  code_builder:
  collection:
  dart_style:
  fetch_client:
  http:
  json_annotation:
  json_serializable:
  lints:
  mockito:
  path:
  petitparser:
  process_runner:
  project_tools:
    git:
      url: https://github.com/xvrh/project_tools.dart.git
      ref: '246a1ac684637f31b9f168b957fca6aad635156f'
  puppeteer:
  shelf:
  shelf_router:
  shelf_static:
  test:
  web:
  yaml:
